avadev/AvaTax-REST-V2-PHP-SDK

- src/AvaTaxClient.php
* Updating with latest swagger for February
> First draft of february release

- composer.json
- src/AvaTaxClient.php
Patch Notes: http://developer.avalara.com/blog/2017/03/08/rest-v2-17-3-patch-notes
> March release

- .gitignore
- composer.json
- src/AvaTaxClient.php
- tests/basicWorkflowTest.php
- tests/bootstrap.php
- tests/phpunit.xml
- tests/test.php
* Updated with 2.17.3-52 swagger source
* Removed vendor/autoload from the client php file
* Some updates to the test suite as per bug reports
> March hotfix for 2.17.3-52 release

- composer.json
- src/AvaTaxClient.php
Patch notes: https://developer.avalara.com/blog/2017/04/25/AvaTax-17-5-patch-notes
> May release for PHP

- composer.json
- src/Constants.php
- src/Methods.php
- src/Models.php
Patch Notes: https://developer.avalara.com/blog/2017/09/22/AvaTax-17-9-patch-notes
> AvaTax 17.9

- src/Constants.php
- src/Methods.php
- src/Models.php
Patch Notes: https://developer.avalara.com/blog/2018/01/04/AvaTax-18-1-patch-notes
> AvaTax 18.1

- src/Client.php
Added new method as withBearerToken method and accordingly made changes in restCall method.
> Added bearer token support in Client.php file

- src/TransactionBuilder.php
> Fixing 'Call to undefined function' error in TransactionBuilder

- src/Constants.php
- src/Methods.php
- src/Models.php
Patch Notes: https://developer.avalara.com/blog/2018/02/05/AvaTax-18-2-patch-notes/
> AvaTax 18.2

- src/Constants.php
- src/Methods.php
- src/Models.php
carrying all changes from REST V2 18.3 update, please review and only merge(if your deployment is tied to master) or deploy when Production releases.
> AvaTax 18.3

- src/TransactionBuilder.php
Simple change to clean up warnings when creating a TransactionBuilder
> Update annotation for DocumentType to string

- composer.json
Permit usage of versions >= 6.0
> Update guzzle dependency

- src/TransactionBuilder.php
Adds a method to the TransactionBuilder to allow it to create a transaction through the CreateOrAdjust Transaction endpoint.
> Add createOrAdjust method to TransactionBuilder

- src/TransactionBuilder.php
> Removed duplicate implementation of withCurrencyCode()

- tests/basicWorkflowTest.php
- Added test cases to assert for the TransactionBuilder's functionality/response to ensure that it is part of the Travis integration test.
> DEVCON 3009

- src/Constants.php
- src/Methods.php
- src/Models.php
Patch notes for 18.9: https://developer.avalara.com/blog/2018/09/10/AvaTax-18-9-patch-notes
> REST API 18.9

- composer.json
> Change PSR-4 to classmap

- src/Constants.php
Patch Notes: https://developer.avalara.com/blog/2018/10/04/AvaTax-18-10-patch-notes/
> AvaTax API 18.10 update

- README.md
- composer.json
- src/Client.php
- src/Constants.php
- src/Methods.php
- src/Models.php
> DEVCON-3371 - API 18.12: Generate PHP SDK

- src/Client.php
- src/Constants.php
- src/Methods.php
- src/Models.php
> Update for v19.1.1

- src/Client.php
- src/Constants.php
- src/Methods.php
- src/Models.php
> Update for 19.4.0

- src/Client.php
- src/Constants.php
- src/Methods.php
- src/Models.php
- src/taxContent/README.txt
- src/taxRatesByZip/README.txt
> Update for 19.5.0

- src/Client.php
- src/Constants.php
- src/Methods.php
- src/Models.php
> Update for 19.6.0

- src/Client.php
- src/Constants.php
- src/Methods.php
- src/Models.php
> Update for 19.7.0

- src/Client.php
- src/Constants.php
- src/Methods.php
- src/Models.php
> Update for 19.8.0

- src/Client.php
- src/Constants.php
- src/Methods.php
- src/Models.php
> Update for 19.9.0

- src/Client.php
> Update for 19.11

- src/Client.php
- src/Constants.php
- src/Methods.php
- src/Models.php
> Update for 20-7-update

- src/Client.php
Added support for ASV and Devport-764
> Fixes for ASV and DEVPORT-764

- src/Client.php
This fix will address issue #115 
Transaction calls are not returning the result with version 20.12
> Fixes for AS-9

- src/ClientExtensionExample.php
update $environment as optional parameter
> Fix for AS-35

- src/LogObject.php
Fix  for - https://github.com/avadev/AvaTax-REST-V2-PHP-SDK/issues/226
> x-correlation-id noting being returned causing LogObject Error
